site_name: Samurai Uprising
site_url: https://shahiutsav.github.io/samurai-uprising/
site_author: ingine
theme:
  name: material
  font:
    text: Murecho # Samurai
    code: "Roboto, sans-serif" # Mafia
  palette:
    scheme: slate
    primary: red # Darker shade of black for dark mode
    accent: orange # Dark red (Blood red)
  features:
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.expand
    - navigation.path
    - navigation.top
    - navigation.indexes
extra_css:
  - assets/css/custom.css # Link to your custom CSS

markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.superfences
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator:
        !!python/name:material.extensions.emoji.to_svg # Page tree


nav:
  - Home:
      - Welcome: index.md
      - Basics: guide.md
      - Guides:
          - War: guides/war.md
      - Tools:
          - TornStats: tools/tornstats.md
          - Discord: tools/discord.md
        # - YATA: tools/yata.md
